name: action-maven-publish-release
author: Samuel Meuli
description: GitHub Action for automatically publishing Maven packages

inputs:
  gpg_private_key:
    description: GPG private key for signing the published artifacts
    required: false
  gpg_passphrase:
    description: Passphrase for the GPG key
    required: false
  nexus_username:
    description: Username (not email!) for your Nexus repository manager account
    required: true
  nexus_password:
    description: Password for your Nexus account
    required: true
  server_id:
    description: Nexus server ID as specified in your project's `nexus-staging-maven-plugin` and `distributionManagement` configurations
    required: false
    default: ossrh
  directory:
    description: Directory of the Maven project which should be deployed
    required: false
  maven_goals_phases:
    description: Maven goals and build phases to execute
    required: false
    default: release:clean release:prepare release:perform
  maven_args:
    description: Additional arguments to pass to the Maven command
    required: false
    default: ""
  activate_profiles:
    description: Activate profiles to pass to the Maven command
    required: false
    default: "release"

runs:
  using: node12
  main: ./index.js

branding:
  icon: upload-cloud
  color: orange
